CREATE DATABASE test;
USE test;

CREATE TABLE partners (
	`id` INT AUTO_INCREMENT NOT NULL,
    `company_name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL, 
    `phone` VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX (`email`) USING BTREE
)
ENGINE = INNODB
CHARACTER SET = UTF8MB4
COLLATE UTF8MB4_UNICODE_CI
;

CREATE TABLE subscribe (
	`id` INT AUTO_INCREMENT NOT NULL,
    `email` VARCHAR(255) NOT NULL, 
    PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX (`email`) USING BTREE
)
ENGINE = INNODB
CHARACTER SET = UTF8MB4
COLLATE UTF8MB4_UNICODE_CI
;